name: drl_policy_gradients
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - absl-py=0.7.0=py36_1000
  - asn1crypto=0.24.0=py36_1003
  - astor=0.7.1=py_0
  - atk=2.25.90=hb9dd440_1002
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - bleach=1.5.0=py36_0
  - c-ares=1.15.0=h14c3975_1001
  - ca-certificates=2019.3.9=hecc5488_0
  - cairo=1.16.0=ha4e643d_1000
  - certifi=2019.3.9=py36_0
  - cffi=1.12.2=py36hf0e25f4_1
  - chardet=3.0.4=py36_1003
  - cryptography=2.5=py36h9d9f1b6_1
  - cycler=0.10.0=py_1
  - dbus=1.13.0=h4e0c4b3_1000
  - decorator=4.3.2=py_0
  - docopt=0.6.2=py_1
  - expat=2.2.5=hf484d3e_1002
  - fontconfig=2.13.1=h2176d3f_1000
  - freetype=2.9.1=h94bbf69_1005
  - gast=0.2.2=py_0
  - gdk-pixbuf=2.36.12=h49783d7_1002
  - gettext=0.19.8.1=h9745a5d_1001
  - glib=2.58.3=hf63aee3_1001
  - gobject-introspection=1.58.2=py36h2da5eee_1000
  - graphite2=1.3.13=hf484d3e_1000
  - gstreamer=1.14.4=h66beb1c_1001
  - gtk2=2.24.31=hb68c50a_1001
  - harfbuzz=2.3.1=h6824563_0
  - html5lib=0.9999999=py36_0
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py36_1000
  - ipykernel=5.1.0=py36h24bf2e0_1002
  - ipython=7.3.0=py36h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.13.3=py36_0
  - jpeg=9c=h14c3975_1001
  - jupyter_client=5.2.4=py_3
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py36h6bb024c_1002
  - libffi=3.2.1=hf484d3e_1005
  - libgcc-ng=7.3.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libiconv=1.15=h14c3975_1004
  - libpng=1.6.36=h84994c4_1000
  - libprotobuf=3.7.0=hdbcaa40_1
  - libsodium=1.0.16=h14c3975_1001
  - libstdcxx-ng=7.3.0=hdf63c60_0
  - libtiff=4.0.10=h648cc4a_1001
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.8=h143f9aa_1005
  - markdown=2.6.11=py_0
  - matplotlib=3.0.3=py36_0
  - matplotlib-base=3.0.3=py36h167e16e_0
  - mkl_fft=1.0.10=py36_0
  - mkl_random=1.0.2=py36_0
  - more-itertools=4.3.0=py36_1000
  - ncurses=6.1=hf484d3e_1002
  - ninja=1.9.0=h6bb024c_0
  - olefile=0.46=py_0
  - openblas=0.2.20=8
  - openssl=1.1.1b=h14c3975_1
  - pango=1.40.14=h4ea9474_1004
  - parso=0.3.4=py_0
  - pcre=8.41=hf484d3e_1003
  - pexpect=4.6.0=py36_1000
  - pickleshare=0.7.5=py36_1000
  - pillow=5.4.1=py36h00a061d_1000
  - pip=19.0.3=py36_0
  - pixman=0.34.0=h14c3975_1003
  - pluggy=0.9.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - protobuf=3.7.0=py36hf484d3e_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py36_1000
  - py=1.8.0=py_0
  - pycparser=2.19=py36_1
  - pygments=2.3.1=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.3.1=py_0
  - pyqt=4.11.4=py36_3
  - pysocks=1.6.8=py36_1002
  - pytest=4.3.0=py36_0
  - python=3.6.7=h381d211_1004
  - python-dateutil=2.8.0=py_0
  - pyyaml=3.13=py36h14c3975_1001
  - pyzmq=18.0.1=py36h0e1adb2_0
  - readline=7.0=hf8c457e_1001
  - requests=2.21.0=py36_1000
  - setuptools=40.8.0=py36_0
  - sip=4.18=py36_1
  - six=1.12.0=py36_1000
  - sqlite=3.26.0=h67949de_1001
  - tensorboard=1.7.0=py36_0
  - termcolor=1.1.0=py_2
  - tk=8.6.9=h84994c4_1000
  - tornado=6.0.1=py36h14c3975_0
  - traitlets=4.3.2=py36_1000
  - urllib3=1.24.1=py36_1000
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=0.14.1=py_0
  - wheel=0.33.1=py36_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h14c3975_1004
  - xorg-libsm=1.2.3=h4937e3b_1000
  - xorg-libx11=1.6.7=h14c3975_1000
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.2=h14c3975_1007
  - xorg-libxext=1.3.3=h14c3975_1004
  - xorg-libxrender=0.9.10=h14c3975_1002
  - xorg-libxt=1.1.5=h14c3975_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.2.5=hf484d3e_1006
  - zlib=1.2.11=h14c3975_1004
  - blas=1.0=mkl
  - grpcio=1.16.1=py36hf8bcb03_1
  - intel-openmp=2019.1=144
  - libopenblas=0.2.20=h9ac9557_7
  - mkl=2018.0.3=1
  - numpy=1.14.5=py36h1b885b7_4
  - numpy-base=1.14.5=py36hdbf6ddf_4
  - qt=4.8.7=2
  - tensorflow=1.7.0=0
  - tensorflow-base=1.7.0=py36hdbcaa40_2
  - pytorch-cpu=1.0.1=py3.6_cpu_2
  - torchvision-cpu=0.2.2=py_3
  - pip:
    - bokeh==0.12.4
    - defusedxml==0.5.0
    - entrypoints==0.3
    - ipywidgets==7.4.2
    - jinja2==2.10
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-console==6.0.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - mlagents==0.7.0
    - mpld3==0.3
    - nbconvert==5.4.1
    - nbformat==4.4.0
    - notebook==5.7.6
    - pandas==0.24.1
    - pandocfilters==1.4.2
    - prometheus-client==0.6.0
    - pyrsistent==0.14.11
    - pytz==2018.9
    - qtconsole==4.4.3
    - scipy==1.2.1
    - send2trash==1.5.0
    - terminado==0.8.1
    - testpath==0.4.2
    - torch==0.4.0
    - torchvision==0.2.2
    - unityagents==0.4.0
    - widgetsnbextension==3.4.2
